### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by ctf0** [toolkito/laravel-social-auto-posting#1]
- larasap facade is not used anywhere, so why its loaded ?
- `facebook/graph-sdk` is already a dependency, so no need to re-install it
- can u tag the package so we can install it, atm the only way is to add it manually and use `composer update`

**Comment by alihesari** [comment]
Thank you for your attention, I will fix this bugs and publish the new version.

**Comment by alihesari** [comment]
Problems have been fixed and the new version has been released.
