### ISSUE TITLE
Dynamic access_token, not in config

### ISSUE THREAD

**Issue by pierrocknroll** [toolkito/laravel-social-auto-posting#13]
Hello,
I have to handle multiple facebook pages and with your implementation, it's a little complicated because the page_access_token is in a configuration file.
It could be great to give the possibility to set it with a method parameter, to avoid to set the configuration value.
Thanks

PS : Same for twitter, if I handle multiple users, I can't hardcode the access_token and access_token_secret on the config file :(

**Comment by softopia-tech** [comment]
Did you find any solution? I want the same thing but i cant pass dynamic tokens.

**Comment by pierrocknroll** [comment]
Use the official packages for Facebook / Twitter. :/

**Comment by softopia-tech** [comment]
`foreach ($_REQUEST['tid'] as $tid) {
            $tokendata = $this->gettokens($tid);
            Config::set('larasap.twitter.access_token', $tokendata['access_token']);
            Config::set('larasap.twitter.access_token_secret', $tokendata['token_secret']);
            SendTo::Twitter($_REQUEST['msg']);
        }`

I am doing something like this.. this is working fine locally, I don't know if this config:: set will change values globally?
