### ISSUE TITLE
 Could not find a matching version of package toolkito/larasap

### ISSUE THREAD

**Issue by RhRU** [toolkito/laravel-social-auto-posting#2]
When trying to install the package via composer I get this message;
 [InvalidArgumentException]
  Could not find a matching version of package toolkito/larasap. Check the package spelling,
   your version constraint and that the package is available in a stability which matches yo
  ur minimum-stability (stable).
PHP version 7.1.12

**Comment by alihesari** [comment]
The new version will be released within a few hours and these issues will be resolved.

**Comment by alihesari** [comment]
Problems have been fixed and the new version has been released.

**Comment by RhRU** [comment]
The issue remains....
