### ISSUE TITLE
Class 'Tooltiko\Larasap\SendTo' not found

### ISSUE THREAD

**Issue by tisuchi** [toolkito/laravel-social-auto-posting#3]
Nice work man. 

However, during using that package, it shows that ```Class 'Tooltiko\Larasap\SendTo' not found``` although I have followed the procedure.

**Comment by alihesari** [comment]
@tisuchi You have mistakes in writing. You should use `Toolkito\Larasap\SendTo`.

**Comment by tisuchi** [comment]
@alihesari 

Is that? Check the documentation. I just follow the doc. 

> First, add the use Tooltiko\Larasap\SendTo; in your controller.

**Comment by alihesari** [comment]
@tisuchi thank you for your attention. I edited and corrected the document. The correct namespace is: `Toolkito\Larasap\SendTo`. Please use this: `use Toolkito\Larasap\SendTo;`

**Comment by tisuchi** [comment]
Well, if I follow the updated namespace, here is the error that I am facing now. 

Call to undefined method Toolkito\Larasap\Facebook\Api::sendLink()

**Comment by alihesari** [comment]
@tisuchi I edited `Toolkito\Larasap\Facebook\Api` class and release the new version (V1.0.2). Please update Larasap package to version 1.0.2

**Comment by alihesari** [comment]
Thanks, @tisuchi for the bug report. Really appreciate it. I'm sorry you are encountering this bug. Has your problem been resolved? If you see a problem, please report it. I will fix the problem as soon as possible.

**Comment by tisuchi** [comment]
@alihesari 

Thanks for your quick update. 

However, right now I am getting another error. It might be a problem from my side, I am confused. 

Here is the error-
Graph returned an error: Error validating access token: Session has expired on Monday, 08-Jan-18 21:00:00 PST. The current time is Tuesday, 09-Jan-18 02:28:32 PST.

**Comment by alihesari** [comment]
@tisuchi Please open new issues for this problem.
