### ISSUE TITLE
Laravel 6.x support 

### ISSUE THREAD

**Issue by ajay-makwana** [toolkito/laravel-social-auto-posting#30]
I'm upgrading my app to Laravel 6.x
But this package is blocking it.
Please update it to work with Laravel 6.x

**Comment by LadyNay** [comment]
> I'm upgrading my app to Laravel 6.x
> But this package is blocking it.
> Please update it to work with Laravel 6.x

BUMP!

**Comment by masoudtajer** [comment]
Thanks for this good package!
when do you update this package for laravel 6 ?

**Comment by Shokhrukh2606** [comment]
Please can you update it to 5.8 i have big project that almost has been done, now this package is required

**Comment by alihesari** [comment]
Fixed #32
