### ISSUE TITLE
lv 5.5 not supported yet?

### ISSUE THREAD

**Issue by Lunberg88** [toolkito/laravel-social-auto-posting#7]
Trying to install package on lv 5.5, but have some issue's.
So question, does this package support laravel 5.5 ?

**Comment by alihesari** [comment]
@Lunberg88 Yes this package supported in Laravel 5.5. 
What error do you get?

**Comment by Lunberg88** [comment]
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - toolkito/larasap V1.0.0 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - toolkito/larasap V1.0.1 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - toolkito/larasap V1.0.2 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.28|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].
    - Installation request for toolkito/larasap ^1.0 -> satisfiable by toolkito/larasap[V1.0.0, V1.0.1, V1.0.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by alihesari** [comment]
@Lunberg88 your Laravel version is 5.4.36. This package required to Laravel 5.5. Please upgrade your Laravel version to 5.5.* 
Also, Install the last version of this package (version 1.0.2)
