### ISSUE TITLE
Facbeook: Graph returned an error: Unknown path components: /me/feed

### ISSUE THREAD

**Issue by StanBarrows** [toolkito/laravel-social-auto-posting#8]
Hey there, 

First of all I'm excited to try out your packages.  Thanks for that! But unfortunately I'm getting the following error.

**Error**
`Graph returned an error: Unknown path components: /me/feed`

**Setup**
I followed your Set-Up on the documentation.

```
   'facebook' => [
        'app_id' => env('FACEBOOK_APP_ID'),
        'app_secret' => env('FACEBOOK_APP_SECRET'),
        'default_graph_version' => '2.11',
        'page_access_token' => env('FACEBOOK_ACCESS_TOKEN')
    ]
```

**Code**
```
use Toolkito\Larasap\SendTo;

public function index()
    {
        SendTo::Facebook(
            'link',
            [
                'link' => 'https://github.com/toolkito/laravel-social-auto-posting',
                'message' => 'Laravel social auto posting'
            ]
        );


        return view('dashboard.index');
    }
```

Cheers Stan

**Comment by StanBarrows** [comment]
Still not working on my side ;)

**Comment by alihesari** [comment]
@StanBarrows Please update package to the new version and test again.

**Comment by DopeEx** [comment]
I installed the current version and have the same problem.
Is there a solution now?

"Graph returned an error: Unknown path components: /me/feed"

**Comment by OdaiTu** [comment]
i have the same error

**Comment by ImaginativeShohag** [comment]
For my case, I missed a "v" in graph version variable.

Right: 'v3.2'
Wrong: '3.2'
